<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Relocation extends \App\Entity\Relocation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'transport_date', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'cat', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'cashier', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'transport_compagnie', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'start_bar', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'end_bar'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'transport_date', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'cat', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'cashier', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'transport_compagnie', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'start_bar', '' . "\0" . 'App\\Entity\\Relocation' . "\0" . 'end_bar'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Relocation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTransportDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransportDate', []);

        return parent::getTransportDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransportDate(\DateTime $transport_date): \App\Entity\Relocation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransportDate', [$transport_date]);

        return parent::setTransportDate($transport_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCat(): ?\App\Entity\Cat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCat', []);

        return parent::getCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCat(?\App\Entity\Cat $cat): \App\Entity\Relocation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCat', [$cat]);

        return parent::setCat($cat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashier(): ?\App\Entity\Cashier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashier', []);

        return parent::getCashier();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashier(?\App\Entity\Cashier $cashier): \App\Entity\Relocation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashier', [$cashier]);

        return parent::setCashier($cashier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransportCompagnie(): ?\App\Entity\TransportCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransportCompagnie', []);

        return parent::getTransportCompagnie();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransportCompagnie(?\App\Entity\TransportCompany $transport_compagnie): \App\Entity\Relocation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransportCompagnie', [$transport_compagnie]);

        return parent::setTransportCompagnie($transport_compagnie);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartBar(): \App\Entity\Bar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartBar', []);

        return parent::getStartBar();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartBar(\App\Entity\Bar $start_bar): \App\Entity\Relocation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartBar', [$start_bar]);

        return parent::setStartBar($start_bar);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndBar(): \App\Entity\Bar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndBar', []);

        return parent::getEndBar();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndBar(\App\Entity\Bar $end_bar): \App\Entity\Relocation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndBar', [$end_bar]);

        return parent::setEndBar($end_bar);
    }

}
