<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Salon extends \App\Entity\Salon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'table_number', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'bar', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'tablets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'table_number', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'bar', '' . "\0" . 'App\\Entity\\Salon' . "\0" . 'tablets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Salon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBar(): \App\Entity\Bar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBar', []);

        return parent::getBar();
    }

    /**
     * {@inheritDoc}
     */
    public function setBar(?\App\Entity\Bar $bar): \App\Entity\Salon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBar', [$bar]);

        return parent::setBar($bar);
    }

    /**
     * {@inheritDoc}
     */
    public function getTableNumber(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTableNumber', []);

        return parent::getTableNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setTableNumber(int $table_number): \App\Entity\Salon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTableNumber', [$table_number]);

        return parent::setTableNumber($table_number);
    }

    /**
     * {@inheritDoc}
     */
    public function addTablets(\App\Entity\Tablet $tablet): \App\Entity\Salon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTablets', [$tablet]);

        return parent::addTablets($tablet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTablets(\App\Entity\Tablet $tablet): \App\Entity\Salon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTablets', [$tablet]);

        return parent::removeTablets($tablet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTablets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTablets', []);

        return parent::getTablets();
    }

    /**
     * {@inheritDoc}
     */
    public function setTablets(\Doctrine\Common\Collections\Collection $tablets): \App\Entity\Salon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTablets', [$tablets]);

        return parent::setTablets($tablets);
    }

}
